version: "2"
services:
  webserver:
    build:
      context: "${ASSETDIR}"
      dockerfile: "${ASSETDIR}/dockerfiles/Dockerfile-moodle-deploy"
      args:
        MOODLE_DOCKER_PHP_VERSION: "${MOODLE_DOCKER_PHP_VERSION}"
    depends_on:
      - db
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
      - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "${MOODLE_DOCKER_DBPASS}"
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
      MOODLE_DOCKER_WEB_PORT: "${MOODLE_DOCKER_WEB_PORT}"
      MOODLE_DOCKER_SMTP_HOST: "${MOODLE_DOCKER_SMTP_HOST}"
      MOODLE_DOCKER_SMTP_SECURITY: "${MOODLE_DOCKER_SMTP_SECURITY}"
      MOODLE_DOCKER_SMTP_AUTHTYPE: "${MOODLE_DOCKER_SMTP_AUTHTYPE}"
      MOODLE_DOCKER_SMTP_USER: "${MOODLE_DOCKER_SMTP_USER}"
      MOODLE_DOCKER_SMTP_PASS: "${MOODLE_DOCKER_SMTP_PASS}"

    ports:
      - "${MOODLE_DOCKER_WEB_PORT}:80"
  db:
    image: postgres:9.6.7
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "${MOODLE_DOCKER_DBPASS}"
      POSTGRES_DB: moodle
