version: "2"
services:
  webserver:
    build:
      context: "${ASSETDIR}"
      dockerfile: "${ASSETDIR}/dockerfiles/Dockerfile-moodle-deploy"
      args:
        MOODLE_DOCKER_PHP_VERSION: "${MOODLE_DOCKER_PHP_VERSION}"
    depends_on:
      - db
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
      - "${PERSISTENTDIR}/letsencrypt:/etc/letsencrypt"
      - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBPASS: "${MOODLE_DOCKER_DBPASS}"
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
      MOODLE_DOCKER_SMTP_HOST: "${MOODLE_DOCKER_SMTP_HOST}"
      MOODLE_DOCKER_SMTP_SECURITY: "${MOODLE_DOCKER_SMTP_SECURITY}"
      MOODLE_DOCKER_SMTP_AUTHTYPE: "${MOODLE_DOCKER_SMTP_AUTHTYPE}"
      MOODLE_DOCKER_SMTP_USER: "${MOODLE_DOCKER_SMTP_USER}"
      MOODLE_DOCKER_SMTP_PASS: "${MOODLE_DOCKER_SMTP_PASS}"
      MOODLE_DOCKER_ADMIN_EMAIL: "$MOODLE_DOCKER_ADMIN_EMAIL"
      MOODLE_DOCKER_SSL: "$MOODLE_DOCKER_SSL"
      MOODLE_DOCKER_DEV_MODE: "$MOODLE_DOCKER_DEV_MODE"
    container_name: moodle_webserver
    ports:
      - "80:80"
      - "443:443"
  db:
    image: postgres:9.6.7
    environment:
      POSTGRES_USER: moodle
      POSTGRES_DB: moodle
      POSTGRES_PASSWORD: "${MOODLE_DOCKER_DBPASS}"
    container_name: moodle_db
